### ISSUE TITLE
Is `getroot` part of the API?

### ISSUE THREAD

**Issue by piever** [JuliaPackaging/RelocatableFolders.jl#11]
Hello! I've been trying to use this to support making apps based on JSServe, see https://github.com/SimonDanisch/JSServe.jl/pull/117.

I would like to just compute the extension of a file stored as a `RelocatableFolders.Path`, without triggering the string conversion logic. I've found that `getroot` does exactly that (see [here](https://github.com/SimonDanisch/JSServe.jl/pull/117/files#diff-b24d4abec9ec1c58ba4a847f98c855303d56d169497ec9548dd9320e8750941bR85)), but it seems to be an internal function. Could it become part of the API?

**Comment by MichaelHatherly** [comment]
I'm fine with exporting `getroot` if it's useful.

**Comment by piever** [comment]
Yes, that would be great!
