### ISSUE TITLE
Release notes for 1.0

### ISSUE THREAD

**Issue by ablaom** [JuliaPackaging/RelocatableFolders.jl#22]
Sorry if this wrong place, but I'm wondering what is breaking in 1.0? I couldn't grep that from the release notes and am examining a compat bump PR at MLJModels.jl. Even better, if someone is able to directly comment on https://github.com/JuliaAI/MLJModels.jl/pull/477 that would be great.

**Comment by MichaelHatherly** [comment]
Nothing user-facing, the package has been pretty stable and "complete" for a fairly long time so I felt it was the right time to tag a 1.0 release.
